# Generated by Django 5.2.1 on 2025-05-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dataset_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
